<?php
/**
 * @category  Collab
 * @package   Collab\SidebarCart
 * @author    Marcin Jędrzejewski <m.jedrzejewski@collab.pl>
 * @copyright 2024 Collab
 * @license   MIT
 */

/**
 * @var Template $block
 * @var SecureHtmlRenderer $secureRenderer
 */
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
?>

<?php
$script = <<<JS
require(["jquery"],function(c){{let e=()=>{var o=c("div.block.block-minicart");o.on("dropdowndialogclose",()=>{document.body.classList.remove("cart-active")}),o.on("dropdowndialogopen",()=>{document.body.classList.add("cart-active")})};["touchstart"].forEach(o=>window.addEventListener(o,e,{once:!0,passive:!0}))}});
JS;
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $script, false) ?>


